# golangci-lint configuration v2
version: "2"

run:
  timeout: 5m
  tests: false
  # Skip generated files
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

issues:
  # Exclude directories from all linting
  exclude-dirs:
    - scripts
    - vendor
    - testdata
  
  # Maximum issues to report
  max-issues-per-linter: 50
  max-same-issues: 10
  
  # Don't hide multiple issues from the same file
  exclude-use-default: false

linters:
  enable:
    # Default linters
    - govet        # Reports suspicious constructs
    - errcheck     # Checks for unchecked errors
    - staticcheck  # Advanced static analysis
    - ineffassign  # Detects ineffectual assignments
    - unused       # Checks for unused code
    
    # Code quality
    - misspell     # Finds misspelled words
    - gosec        # Security checker
    - goconst      # Finds repeated strings that could be constants
    - gocyclo      # Cyclomatic complexity checker
    - dupl         # Code duplication checker
    - revive       # Fast, configurable linter
    
    # Best practices
    - bodyclose    # Checks HTTP response body is closed
    - noctx        # Finds sending HTTP request without context
    - unconvert    # Removes unnecessary type conversions
    - gofmt        # Checks code formatting
    - goimports    # Checks import formatting
    - godot        # Checks comment punctuation
    
    # Performance
    - prealloc     # Suggests slice pre-allocation
    - exportloopref # Checks for pointers to enclosing loop variables

  disable:
    - depguard     # Too restrictive for general use
    - gochecknoglobals # We use some globals
    - gochecknoinits   # Init functions are sometimes needed
    - gomnd        # Magic numbers are sometimes clear in context
    - wsl          # Too opinionated about whitespace

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
  
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write
  
  staticcheck:
    checks: ["all"]
  
  misspell:
    locale: US
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input
  
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  
  godot:
    scope: all
    exclude:
      - "^fixme:"
      - "^todo:"
  
  goimports:
    local-prefixes: github.com/agentstation/tokenizer
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: true