version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: tokenizer
    main: ./cmd/tokenizer
    binary: tokenizer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
    ldflags:
      - -s -w
      - -X github.com/agentstation/tokenizer/cmd/tokenizer.version={{.Version}}
      - -X github.com/agentstation/tokenizer/cmd/tokenizer.commit={{.Commit}}
      - -X github.com/agentstation/tokenizer/cmd/tokenizer.date={{.Date}}
      - -X github.com/agentstation/tokenizer/cmd/tokenizer.builtBy=goreleaser

archives:
  - id: tokenizer
    ids:
      - tokenizer
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: agentstation
    name: tokenizer
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## tokenizer v{{.Version}}
    
    ### Installation
    
    #### Download Binary
    Download the appropriate binary for your platform from the assets below.
    
    #### Using Go
    ```bash
    go install github.com/agentstation/tokenizer/cmd/tokenizer@v{{.Version}}
    ```
    
    #### Verify Checksums
    ```bash
    # Download checksums.txt and the binary, then:
    sha256sum -c checksums.txt
    ```

# Optional: Homebrew tap configuration
# brews:
#   - name: tokenizer
#     repository:
#       owner: agentstation
#       name: homebrew-tap
#     directory: Formula
#     homepage: https://github.com/agentstation/tokenizer
#     description: "High-performance Llama 3 tokenizer in Go"
#     license: "MIT"