blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/agentstation/tokenizer/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/agentstation/tokenizer/blob/master/README.md
    about: Check out the documentation for usage information
  - name: Community Support
    url: https://github.com/agentstation/tokenizer/discussions/categories/q-a
    about: Get help from the community